# Question 9: Matrix Multiplication

In [5]:
using LinearAlgebra
using Random
Random.seed!(1)
A = round.(10*rand(2,3))
B = round.(10*rand(3,4))
typeof(A)
A*B

2×4 Matrix{Float64}:
 127.0  87.0  3.0  95.0
  71.0  61.0  9.0  80.0

## 9(a) `my_mult_by_cols`

In [ ]:
function my_mult_by_cols(A::Matrix, B::Matrix)::Matrix
  if size(A, 2) != size(B, 1)
    throw(DimensionMismatch("Inner dimension must be equal: got $(size(A)) and $(size(B))"))
  end

  C = zeros((size(A)[1],size(B)[2]))

  for j in 1:size(C, 2)
    for k in 1:size(A, 2)
      C[:,j] += B[k,j] * A[:,k]
    end
  end

  return C
end

my_mult_by_cols(A, B)

2×4 Matrix{Float64}:
 127.0  87.0  3.0  95.0
  71.0  61.0  9.0  80.0

I'm having a hard time with this, trying to work out exactly what I need to loop through. I discovered the eachcol and eachrow functions. But then, trying to get the B element to match up with the A col vector... ach its tough. Now I've discovered matrix index slicing! A little more powerful, I think. New approach: let's think mathematically. I've developed the formula I'm trying to implement:
$$
  c_j = \sum_{k=1}^{m} B_{k,j}A_{:,j}
$$
I'm going to try and develop the function by translating the formula from math to code.

Yes, that was much easier and much more congurant with my ways of thinking.

## 9(b) `my_mult_by_rows`

In [ ]:
function my_mult_by_rows(A::Matrix, B::Matrix)::Matrix
  if size(A, 2) != size(B, 1)
    throw(DimensionMismatch("Inner dimension must be equal: got $(size(A)) and $(size(B))"))
  end

  C = zeros((size(A)[1],size(B)[2]))

  for i in 1:size(C, 1)
    for k in 1:size(B, 1)
      C[i,:] += A[i,k] * B[k,:]
    end
  end

  return C
end

my_mult_by_rows(A, B)

2×4 Matrix{Float64}:
 127.0  87.0  3.0  95.0
  71.0  61.0  9.0  80.0

Now that I know how much easier working with the math is, I'm just going to start by considering the approriate formula, namely
$$
  c_i = \sum_{k=1}^{n} A_{i,k}B_{k,:}
$$
I'll also start writing my function with the same error handling and set up I had in `my_mult_by_cols`.

Nice! With my experience and code from 9(a), I was able to implement the function by just swapping some variables around in less than 5 minutes.

## 9(c) `my_mult_sum_outer_products`

In [86]:
# ORIGINAL CODE
# function my_mult_sum_outer_products(A::Matrix, B::Matrix)::Matrix
#   if size(A, 2) != size(B, 1)
#     throw(DimensionMismatch("Inner dimension must be equal: got $(size(A)) and $(size(B))"))
#   end

#   C = zeros((size(A)[1],size(B)[2]))

#   for j in 1:size(A,2)
#     C += A[:,j] * transpose(B[j,:])
#   end

#   return C
# end

# FILTHY ARRAY COMPREHENSION
# function my_mult_sum_outer_products(A::Matrix, B::Matrix)::Matrix
#   if size(A, 2) != size(B, 1)
#     throw(DimensionMismatch("Inner dimension must be equal: got $(size(A)) and $(size(B))"))
#   end
#   return sum([A[:,j] * transpose(B[j,:]) for j in 1:size(A,2)])
# end

# FINAL FORM
my_mult_sum_outer_products(A::Matrix, B::Matrix)::Matrix = (size(A, 2) == size(B, 1) || throw(DimensionMismatch("Inner dimension must be equal: got $(size(A)) and $(size(B))"))) && sum(A[:,j] * transpose(B[j,:]) for j in 1:size(A,2))

my_mult_sum_outer_products(A, B)

2×4 Matrix{Float64}:
 127.0  87.0  3.0  95.0
  71.0  61.0  9.0  80.0

This time they gave me the courtesy of giving me the math I need to implement,
$$
  AB = \sum_{j=1}^{m} A_{:,j}B_{J,:}^\top
$$
Let's Implement it!

I was a little worried, but then I typed transpose into a cell, and autocomplete revealed to me that an easy to use transpose function exists. Once I knew that, the function was really easy to write.

I think this is a prime candidate for a filthy array comprehension...

yes! I was hoping the sum command would work like that haha. PERFECT.

Ok I did some research, and I think I can bring the size check into the return statement with a short-circuit error check, like was shown in the lectures. Also I learned that sum works matrix-wise with generators, so I don't even need the comprehension! I can just throw the generator directly into `sum`. Finally, I saw in the Julia Express alternative ways to define functions, including in one line, omiting the `function` and `end` keywords. Truly, a one line function. I present, `my_mult_sum_outer_product`'s final form.